/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mintic.videoclub.swings;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Joselo
 */
public class VistaPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form VistaPeliculas
     */
    public VistaPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMOpcionesPelicula = new javax.swing.JPopupMenu();
        jMIEditarPelicula = new javax.swing.JCheckBoxMenuItem();
        jMIAlquilarPelicula = new javax.swing.JCheckBoxMenuItem();
        jMIDevolverPelicula = new javax.swing.JCheckBoxMenuItem();
        jSPTabla = new javax.swing.JScrollPane();
        jTInfoPelicuas = new javax.swing.JTable();
        jMBBarraPrincipal = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();
        jMOperaciones = new javax.swing.JMenu();
        jMIAgregarPelicula = new javax.swing.JMenuItem();

        jMIEditarPelicula.setSelected(true);
        jMIEditarPelicula.setText("Editar Pelicula");
        jMIEditarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEditarPeliculaActionPerformed(evt);
            }
        });
        jPMOpcionesPelicula.add(jMIEditarPelicula);

        jMIAlquilarPelicula.setSelected(true);
        jMIAlquilarPelicula.setText("Alquilar Pelicula");
        jPMOpcionesPelicula.add(jMIAlquilarPelicula);

        jMIDevolverPelicula.setSelected(true);
        jMIDevolverPelicula.setText("Devolver Pelicula");
        jPMOpcionesPelicula.add(jMIDevolverPelicula);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de peliculas");
        setBounds(new java.awt.Rectangle(150, 60, 500, 500));
        setName("listadoPeliculas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(804, 604));
        setResizable(false);

        jTInfoPelicuas.setAutoCreateRowSorter(true);
        jTInfoPelicuas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID pelicula", "Nombre", "Duracion (min)", "Descripcion", "Año", "Categoria", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTInfoPelicuas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTInfoPelicuas.setComponentPopupMenu(jPMOpcionesPelicula);
        jSPTabla.setViewportView(jTInfoPelicuas);

        jMArchivo.setText("Archivo");

        jMISalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-close-window-16.png"))); // NOI18N
        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMArchivo.add(jMISalir);

        jMBBarraPrincipal.add(jMArchivo);

        jMOperaciones.setText("Operaciones");

        jMIAgregarPelicula.setText("Agregar Pelicula");
        jMIAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarPeliculaActionPerformed(evt);
            }
        });
        jMOperaciones.add(jMIAgregarPelicula);

        jMBBarraPrincipal.add(jMOperaciones);

        setJMenuBar(jMBBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarPeliculaActionPerformed
        NuevaPelicula nuevaPelicula = new NuevaPelicula(this, true);
        nuevaPelicula.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosed(WindowEvent e){
                //Ejecutar la actualizacion de las peliculas
            }
});
        nuevaPelicula.setVisible(true);
    }//GEN-LAST:event_jMIAgregarPeliculaActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        
        //System.exit(0);
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMIEditarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEditarPeliculaActionPerformed
        EditarPelicula editarPelicula = new EditarPelicula(this, true);
        editarPelicula.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosed(WindowEvent e){
                //Ejecutar la actualizacion de las peliculas
            }
});
        editarPelicula.setVisible(true);
    }//GEN-LAST:event_jMIEditarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenuBar jMBBarraPrincipal;
    private javax.swing.JMenuItem jMIAgregarPelicula;
    private javax.swing.JCheckBoxMenuItem jMIAlquilarPelicula;
    private javax.swing.JCheckBoxMenuItem jMIDevolverPelicula;
    private javax.swing.JCheckBoxMenuItem jMIEditarPelicula;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMOperaciones;
    private javax.swing.JPopupMenu jPMOpcionesPelicula;
    private javax.swing.JScrollPane jSPTabla;
    private javax.swing.JTable jTInfoPelicuas;
    // End of variables declaration//GEN-END:variables
}
